init:
    cargo install wasm-pack

[linux]
wasm-clippy:
    cargo clippy --target=wasm32-unknown-unknown -- -D warnings -A clippy::uninlined-format-args

[macos]
wasm-clippy:
    AR=/usr/local/opt/llvm/bin/llvm-ar CC=/usr/local/opt/llvm/bin/clang cargo clippy --target=wasm32-unknown-unknown -- -D warnings -A clippy::uninlined-format-args

[linux]
wasm-test:
    wasm-pack test --headless --firefox

[macos]
wasm-test:
    AR=/usr/local/opt/llvm/bin/llvm-ar CC=/usr/local/opt/llvm/bin/clang wasm-pack test --headless --firefox
