name: Build Language bindings
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      kotlin:
        required: false
        type: boolean
        default: false
      swift:
        required: false
        type: boolean
        default: false
      python:
        required: false
        type: boolean
        default: false
      csharp:
        required: false
        type: boolean
        default: false
      golang:
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      repository:
        description: 'sdk repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      kotlin:
        required: false
        type: boolean
        default: false
      swift:
        required: false
        type: boolean
        default: false
      python:
        required: false
        type: boolean
        default: false
      csharp:
        required: false
        type: boolean
        default: false
      golang:
        required: false
        type: boolean
        default: false

jobs:
  build-language-bindings:
    runs-on: ubuntu-latest
    if: ${{ inputs.csharp || inputs.golang || inputs.python || inputs.swift }}
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}
  
      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
  
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "27.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Swift binding
        if: ${{ inputs.swift }}
        working-directory: libs/sdk-bindings
        run: |
          cargo run --bin uniffi-bindgen generate src/breez_sdk.udl --no-format --language swift --out-dir bindings-swift/Sources/BreezSDK
          mv bindings-swift/Sources/BreezSDK/breez_sdk.swift bindings-swift/Sources/BreezSDK/BreezSDK.swift
      
      - name: Archive Swift binding
        if: ${{ inputs.swift }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-swift
          path: libs/sdk-bindings/bindings-swift/Sources/BreezSDK/*
      
      - name: Build Python binding
        if: ${{ inputs.python }}
        working-directory: libs/sdk-bindings
        run: |
            cargo run --bin uniffi-bindgen generate src/breez_sdk.udl --language python -o ffi/python
    
      - name: Archive Python binding
        if: ${{ inputs.python }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-python
          path: libs/sdk-bindings/ffi/python/breez_sdk.py

      - name: Build C# binding
        if: ${{ inputs.csharp }}
        working-directory: libs/sdk-bindings
        run: |
          cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs --tag v0.9.1+v0.28.3
          uniffi-bindgen-cs src/breez_sdk.udl -o ffi/csharp -c ./uniffi.toml
      
      - name: Archive C# binding
        if: ${{ inputs.csharp }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-csharp
          path: libs/sdk-bindings/ffi/csharp/breez_sdk.cs
    
      - name: Build golang binding
        if: ${{ inputs.golang }}
        working-directory: libs/sdk-bindings
        run: |
          cargo install uniffi-bindgen-go --git https://github.com/NordSecurity/uniffi-bindgen-go --tag v0.3.0+v0.28.3
          uniffi-bindgen-go src/breez_sdk.udl -o ffi/golang -c ./uniffi.toml
  
      - name: Archive golang binding
        if: ${{ inputs.golang }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-golang
          path: libs/sdk-bindings/ffi/golang/breez_sdk/breez_sdk.*

  build-language-bindings-uniffi-25:
    runs-on: ubuntu-latest
    if: ${{ inputs.kotlin }}
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "27.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: uniffi-25
          workspaces: lib

      - name: Build Kotlin binding
        if: ${{ inputs.kotlin }}
        working-directory: libs/sdk-bindings
        run: |
          cargo run --no-default-features --features=uniffi-25 --bin uniffi-bindgen generate src/breez_sdk.udl --language kotlin -o ffi/kotlin
  
      - name: Archive Kotlin binding
        if: ${{ inputs.kotlin }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-kotlin
          path: libs/sdk-bindings/ffi/kotlin/breez_sdk/breez_sdk.kt

      - name: Archive Kotlin multiplatform binding
        if: ${{ inputs.kotlin }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-kotlin-multiplatform
          path: libs/sdk-bindings/ffi/kmp/*
