name: Publish Kotlin multiplatform Bindings
on:
  workflow_call:
    inputs:
      repository:
        description: 'sdk repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      package-version:
        description: 'version for the gradle library (MAJOR.MINOR.BUILD)'
        required: true
        type: string
      publish:
        description: 'value indicating whether to publish to maven.'
        required: true
        type: boolean
        default: false
    secrets:
      BREEZ_MVN_USERNAME:
        description: 'username for gradlew publish'
        required: true
      BREEZ_MVN_PASSWORD:
        description: 'password for gradlew publish'
        required: true

jobs:
  build-package:
    runs-on: macOS-latest
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/download-artifact@v4
        with:
          name: sdk-bindings-android-jniLibs
          path: libs/sdk-bindings/bindings-kotlin-multiplatform/breez-sdk-kmp/src/androidMain/jniLibs

      - uses: actions/download-artifact@v4
        with:
          name: bindings-kotlin-multiplatform
          path: libs/sdk-bindings/bindings-kotlin-multiplatform/breez-sdk-kmp/src

      - name: Move files
        working-directory: libs/sdk-bindings/bindings-kotlin-multiplatform/breez-sdk-kmp/src
        run: |
          mkdir -p androidMain/kotlin/breez_sdk
          mkdir -p commonMain/kotlin/breez_sdk
          mkdir -p jvmMain/kotlin/breez_sdk
          mkdir -p nativeMain/kotlin/breez_sdk
          mv main/kotlin/breez_sdk/breez_sdk.android.kt androidMain/kotlin/breez_sdk/
          mv main/kotlin/breez_sdk/breez_sdk.common.kt commonMain/kotlin/breez_sdk/
          mv main/kotlin/breez_sdk/breez_sdk.jvm.kt jvmMain/kotlin/breez_sdk/
          mv main/kotlin/breez_sdk/breez_sdk.native.kt nativeMain/kotlin/breez_sdk/
          rm -r main/kotlin/breez_sdk

      - uses: actions/download-artifact@v4
        with:
          name: sdk-bindings-aarch64-apple-ios
          path: libs/sdk-bindings/bindings-kotlin-multiplatform/breez-sdk-kmp/src/lib/ios-arm64

      - uses: actions/download-artifact@v4
        with:
          name: sdk-bindings-aarch64-apple-ios-sim
          path: libs/sdk-bindings/bindings-kotlin-multiplatform/breez-sdk-kmp/src/lib/ios-simulator-arm64

      - uses: actions/download-artifact@v4
        with:
          name: sdk-bindings-x86_64-apple-ios
          path: libs/sdk-bindings/bindings-kotlin-multiplatform/breez-sdk-kmp/src/lib/ios-simulator-x64

      - name: Build Kotlin Multiplatform project
        working-directory: libs/sdk-bindings/bindings-kotlin-multiplatform
        env:
          ORG_GRADLE_PROJECT_libraryVersion: ${{ inputs.package-version || '0.0.1' }}
        run: ./gradlew :breez-sdk-kmp:assemble

      - name: Archive aar
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-multiplatform-release.aar
          path: libs/sdk-bindings/bindings-kotlin-multiplatform/breez-sdk-kmp/build/outputs/aar/breez-sdk-kmp-release.aar
        
      - name: Publish artifacts
        if: ${{ inputs.publish }}
        working-directory: libs/sdk-bindings/bindings-kotlin-multiplatform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
          BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
        run: |
          ./gradlew publish -PlibraryVersion=${{ inputs.package-version }} -PbreezReposiliteUsername="$BREEZ_MVN_USERNAME" -PbreezReposilitePassword="$BREEZ_MVN_PASSWORD"
